name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or other LTS version
      - name: Install
        run: npm install
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-output-to-deploy
          path: ./out
    
