name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    uses: ./.github/workflows/template-test-build-and-publish-artifact.yml
    with:
      artifact-name: build-output-to-deploy
      
  deploy_dev:
    name: Deploy CI
    needs: build_and_test
    uses: ./.github/workflows/template-deploy-azure-static-web-app.yml
    with:
      environment: Development
      artifact-name: build-output-to-deploy
    secrets: inherit
          
  deploy_prod:
    name: Deploy Prod
    needs: deploy_dev
    uses: ./.github/workflows/template-deploy-azure-static-web-app.yml
    with:
      artifact-name: build-output-to-deploy
    secrets: inherit
