name: Build Storybook and Publish Artifact

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string

jobs:
  build:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or other LTS version
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build-storybook
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ./storybook-static
