name: Deploy Artifacts

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ./
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_MOSS_06144730F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "./"
          is_static_export: true
          deployment_environment: ${{ inputs.environment }}
          skip_app_build: true
          skip_api_build: true
