name: Test, Build and Publish Artifact

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or other LTS version
      - name: Install
        run: npm install
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Publish Test
        run: sed -n '/<table class="coverage-summary">/,/<\/table>/p' ./coverage/lcov-report/index.html >> $GITHUB_STEP_SUMMARY
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ./out
